esphome:
  name: wood-boiler
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Enable Home Assistant API
api:

# Enable MQTT support
#mqtt:
#  broker: !secret mqtt_addr
#  username: !secret mqtt_user
#  password: !secret mqtt_password

# Enable logging
logger:

# Enable OTA updates
ota:

# Enable SPI for sensors
spi:
  miso_pin: D6
  clk_pin: D5

sensor:
  - platform: max31855
    name: "Wood Boiler Temperature"
    cs_pin: D8
    update_interval: 60s
